%%Ve du lieu duoi dang WaveForm va Linear Spectrum
subplot(2,3,1)
plot(t, y)
xlabel('Second')
ylabel('Bien do')
title('Quy \\a WaveForm')
subplot(2,3,4)
plot(tt, dfty)
xlabel('Hz')
ylabel('dB')
title('Linear Spectrum')

subplot(2,3,2)
plot(t2, y2)
xlabel('Second')
ylabel('Bien do')
title('Son \\o WaveForm')
subplot(2,3,5)
plot(tt2, dfty2)
xlabel('Hz')
ylabel('dB')
title('Linear Spectrum')

subplot(2,3,3)
plot(t3, y3)
xlabel('Second')
ylabel('Bien do')
title('Thu \\e WaveForm')
subplot(2,3,6)
plot(tt3, dfty3)
xlabel('Hz')
ylabel('dB')
title('Linear Spectrum')